### ISSUE TITLE
Missing figures folders for graphics

### ISSUE THREAD

**Issue by janoxakes** [mynameisjanus/686xMachineLearning#1]
Hi,

First of all, great work and thank you very much for sharing it.
I have tried to generate the pdf myself and the figures are missing. For the probability cheatsheet i got them from the source cited, but for this one I could not find them. It can replicate them as pictures, but if you still have them available please upload them.

**Comment by mynameisjanus** [comment]
Hi,
Thanks! I've uploaded them already.
